language: node_js
sudo: false
node_js:
  - "stable"
script:
  - npm run ig
  - npm run u
  - npm t
  - npm run d
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master    
before_deploy:
  - touch .nojekyll
  - sed -i '/doc/d' .gitignore